name: limit_kuota_by5
description: Limit Kuota App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.0.0
  fl_chart: ^0.68.0
  pie_chart: ^5.4.0
  intl: ^0.18.1
  sqflite: ^2.3.0
  path: ^1.8.3
  android_intent_plus: ^6.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true